# uhttp-crypto/.github/actions/setup/action.yaml
name: 'Setup Products'
description: 'Setup Products projects'
inputs:
  node-version:
    description: 'Node version to use'
    required: true
  GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY:
    description: 'Google credentials'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
          node-version: '20'

    - name: Install Yarn
      shell: /bin/bash
      run: npm install -g yarn

    - name: Set up Google Cloud Credentials
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ inputs.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}

    - name: Login Google Artifact Registry
      uses: docker/login-action@v3
      with:
        registry: europe-west3-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: ./yarn.lock
          registry-url: https://europe-west3-npm.pkg.dev/hoprassociation/npm

    - name: Install dependencies
      shell: /bin/bash
      run: yarn --frozen-lockfile
