# hoprnet/uhttp-crypto/.github/actions/setup@main
name: 'Setup uhttp repository'
description: 'Setup Products projects'
inputs:
    node-version:
        description: 'Node version to use'
        required: true
    google-credentials:
        description: 'Google credentials taken from secret GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY'
        required: true
outputs:
  access_token:
    description: "GCP Access token"
runs:
    using: 'composite'
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
              node-version: '20'

        - name: Install Yarn
          shell: bash
          run: npm install -g yarn

        - name: Set up Google Cloud Credentials
          id: auth
          uses: google-github-actions/auth@v2
          with:
              export_environment_variables: true
              create_credentials_file: true
              token_format: 'access_token'
              credentials_json: ${{ inputs.google-credentials }}

        - name: Login Google Container Registry
          uses: docker/login-action@v3
          with:
              registry: europe-west3-docker.pkg.dev
              username: oauth2accesstoken
              password: ${{ steps.auth.outputs.access_token }}

        - name: Set up Google Cloud SDK
          uses: google-github-actions/setup-gcloud@v2
          with:
              project_id: hoprassociation
              install_components: beta

        - name: Login Google Artifact Registry
          shell: bash
          run: npm run login

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
              node-version: '20'
              cache: 'yarn'
              cache-dependency-path: ./yarn.lock
              registry-url: https://europe-west3-npm.pkg.dev/hoprassociation/npm

        - name: Install dependencies
          shell: bash
          run: yarn --frozen-lockfile

        - name: Retrieve GCP Authenticated Account Info
          shell: bash
          run: echo "access_token=${{ steps.auth.outputs.access_token }}" >> $GITHUB_OUTPUT
