# hoprnet/uhttp-crypto/.github/actions/setup@main
name: 'Setup uhttp repository'
description: 'Setup Products projects'
inputs:
    node-version:
        description: 'Node version to use'
        required: true
    google-credentials:
        description: 'Google credentials taken from secret GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY'
        required: true

runs:
    using: 'composite'
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
              node-version: '20'

        - name: Install Yarn
          shell: bash
          run: npm install -g yarn

        - name: Set up Google Cloud Credentials
          id: auth
          uses: google-github-actions/auth@v2
          with:
              token_format: 'access_token'
              credentials_json: ${{ inputs.google-credentials }}

        - name: Login Google Artifact Registry
          shell: bash
          run: npm run login

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
              node-version: '20'
              cache: 'yarn'
              cache-dependency-path: ./yarn.lock
              registry-url: https://europe-west3-npm.pkg.dev/hoprassociation/npm

        - name: Install dependencies
          shell: bash
          run: yarn --frozen-lockfile
