name: Build

on:
  pull_request:
    types: [synchronize, opened, reopened]

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: self-hosted-hoprnet-small

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: ./yarn.lock
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Building
        run: yarn build

      - name: Linting
        run: yarn lint:ci

      - name: Formatting
        run: yarn format:ci

      - name: Testing
        run: yarn test

      - name: Update version
        run: |
          NEW_VERSION=$(node -p "require('./package.json').version")-pr.${{ github.event.pull_request.number }}+$(date +%Y%m%d%H%M%S)
          npm version ${NEW_VERSION} --no-git-tag-version

      - name: Publish to npm
        run: yarn publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
