name: Merge PR

on:
    pull_request:
        types:
            - closed
        branches:
            - main

concurrency:
    group: merge
    cancel-in-progress: false

jobs:
    merge:
        name: Merge PR
        runs-on: self-hosted-hoprnet-small
        if: github.event.pull_request.merged == true

        steps:
            - name: Setup uhttp repository
              id: setup
              uses: hoprnet/uhttp-crypto/.github/actions/setup@ausias/test-pipelines
              with:
                  node-version: 20
                  google-credentials: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}

            - name: Publish alpha version
              run: |
                  PR_VERSION=$(node -p "require('./package.json').version")-pr.${{ github.event.pull_request.number }}
                  npm version ${PR_VERSION} --no-git-tag-version
                  yarn publish --tag alpha
              env:
                  NODE_AUTH_TOKEN: ${{ steps.setup.outputs.access_token }}

            - name: Unpublish PR commit versions
              run: |
                  gcloud artifacts versions list --repository=npm --location=europe-west3 --project=hoprassociation --package @hoprnet/uhttp-crypto --format=json 2> /dev/null | jq -r ' .[] | select(.name | contains("-pr.${{ github.event.pull_request.number }}-")).name' > pr_commit_versions.txt
                  while read -r version; do
                    version_number=$(sed 's/.*versions\///' <<< $version)
                    echo "Unpublishing commit version: $version"
                    gcloud artifacts versions delete --delete-tags --quiet --repository=npm --location=europe-west3 --project=hoprassociation --package @hoprnet/uhttp-crypto $version_number
                  done < pr_commit_versions.txt
