name: Close release

on:
    workflow_dispatch:

concurrency:
    group: release
    cancel-in-progress: false

jobs:
    release:
        name: Close release
        runs-on: self-hosted-hoprnet-small

        steps:
            - name: Setup uhttp repository
              id: setup
              uses: hoprnet/uhttp-crypto/.github/actions/setup@ausias/test-pipelines
              with:
                  node-version: 20
                  google-credentials: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}

            - name: Check version
              run: |
                  PACKAGE_VERSION=$(node -p "require('./package.json').version")
                  git fetch --all --tags
                  if git tag -l ${PACKAGE_VERSION} | grep ${PACKAGE_VERSION};
                  then 
                    echo "Git tag ${PACKAGE_VERSION}; alreay exists"
                    exit 1
                  else
                    git tag v${PACKAGE_VERSION}
                    git push origin v${PACKAGE_VERSION}
                  fi

            - name: Building
              run: yarn build

            - name: Linting
              run: yarn lint:ci

            - name: Formatting
              run: yarn format:ci

            - name: Testing
              run: yarn test

            - name: Publish to npm
              run: yarn publish --tag latest
              env:
                  NODE_AUTH_TOKEN: ${{ steps.setup.outputs.access_token }}

            - name: Unpublish PR versions
              run: |
                  PACKAGE_VERSION=$(node -p "require('./package.json').version")
                  gcloud artifacts versions list --repository=npm --location=europe-west3 --project=hoprassociation --package=@hoprnet/uhttp-crypto --format=json 2> /dev/null | jq --arg version "${PACKAGE_VERSION}-pr." -r ' .[] | select(.name | contains($version)).name' > pr_versions.txt
                  while read -r version; do
                    version_number=$(sed 's/.*versions\///' <<< $version)
                    echo "Unpublishing PR version: $version_number"
                    gcloud artifacts versions delete --delete-tags --quiet --repository=npm --location=europe-west3 --project=hoprassociation --package @hoprnet/uhttp-crypto $version_number
                  done < pr_versions.txt
